Add more configuration for OStree repos
ostree requires that the `config' file has the
[core] section identifier and the repo_version attributes.

Otherwise it gives errors like:

Couldn't parse config file: Key file does not start with a group

or

error: Key file does not have key 'repo_version' in group 'core'